name: Sync To Gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:muaimingjun/node.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:muaimingjun/node.git


  resources:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitcode
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:muaimingjun/node.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitcode.com:muaimingjun/node.git